# -*- coding: utf-8 -*-
"""codigo_trab_pratico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoJFodPo04CT1npGytv2g3eMbzeIiic6
"""

# -- coding: utf-8 --
import random
from datetime import datetime
import re
import pandas as pd
import os
import numpy as np

# ============================
# 1. CONFIGURAÇÕES E SEGURANÇA
# ============================

CHAVE_ADMIN = "intercursos1234"

def login_administrador():
    """Solicita e verifica a chave de acesso do Administrador."""
    print("\n🔐 LOGIN NECESSÁRIO")
    senha_digitada = input("Digite a chave de acesso: ")
    if senha_digitada == CHAVE_ADMIN:
        print("✅ Acesso concedido!")
        return True
    else:
        print("❌ Senha incorreta.")
        return False

# --- LISTAS E MAPEAMENTOS ---

# Mapeamento Numérico de Esportes
ESPORTES_MAP = {
    1: "Futsal", 2: "Handebol", 3: "Vôlei", 4: "Tênis de campo",
    5: "Basquete", 6: "Vôlei de areia", 7: "Beach Tennis", 8: "Futevôlei"
}
ESPORTES_PERMITIDOS = list(ESPORTES_MAP.values())

# Regra de Quórum Mínimo
MINIMO_JOGADORES = {
    "Futsal": 5, "Basquete": 5, "Handebol": 7, "Vôlei": 6,
    "Vôlei de areia": 2, "Beach Tennis": 2, "Futevôlei": 2, "Tênis de campo": 2
}

# Mapeamento Numérico de Gênero
GENERO_MAP = {1: "masculino", 2: "feminino"}
GENERO_PERMITIDO = list(GENERO_MAP.values())

# Mapeamento Numérico de Secretarias
SECRETARIAS_MAP = {
    1: "AAACSC (CAASO)", 2: "SAMECA", 3: "Pró-Produção", 4: "SAAero",
    5: "SACivil", 6: "SAPA", 7: "SA-SEL", 8: "SAEMM",
    9: "SAdEM", 10: "SAAU", 11: "SACIM", 12: "SACEx"
}
SECRETARIAS_VALIDAS = list(SECRETARIAS_MAP.values())

# De-Para: Nome na Planilha de Disponibilidade -> Nome no Sistema
DE_PARA_MODALIDADES = {
    "Fut Volei Masculino": "Futevôlei Masculino",
    "Fut Volei Feminino": "Futevôlei Feminino",
    "Volei de areia Masculino": "Vôlei de areia Masculino",
    "Volei de areia Feminino": "Vôlei de areia Feminino",
    "Beach Tenis Masculino": "Beach Tennis Masculino",
    "Beach Tenis Feminino": "Beach Tennis Feminino",
    "Futsal Masculino": "Futsal Masculino",
    "Futsal Feminino": "Futsal Feminino",
    "Basquete Masculino": "Basquete Masculino",
    "Basquete Feminino": "Basquete Feminino",
    "Handebol Masculino": "Handebol Masculino",
    "Handebol Feminino": "Handebol Feminino",
    "Tenis de Campo Masculino": "Tênis de campo Masculino",
    "Tenis de Campo Feminino": "Tênis de campo Feminino",
    "Volei Masculino": "Vôlei Masculino",
    "Volei Feminino": "Vôlei Feminino"
}

# ============================
# 2. BANCOS DE DADOS
# ============================

BIBLIOTECA_ATLETAS = {}
BIBLIOTECA_ADMINISTRADORES = {}
BIBLIOTECA_CONFRONTOS = {}
AGENDA = []
DISPONIBILIDADE_TIMES = {}

# ============================
# 3. CLASSES (MODELOS)
# ============================

class Administrador:
    def _init_(self, admin_id, nome, contato, secretaria_resp):
        self.admin_id = admin_id
        self.nome = nome
        self.contato = contato
        self.secretaria_resp = secretaria_resp
    def _str_(self):
        return f"ID: {self.admin_id} | Nome: {self.nome} | Contato: {self.contato} | Resp: {self.secretaria_resp}"

class Atleta:
    def _init_(self, atleta_id, nome, contato, sexo, esporte_interesse, time_secretaria):
        self.atleta_id = atleta_id
        self.nome = nome
        self.contato = contato
        self.sexo = sexo.title()
        self.esporte_interesse = esporte_interesse
        self.modalidade_final = f"{esporte_interesse} {self.sexo}"
        self.time_secretaria = time_secretaria.strip().title()
    def _str_(self):
        return f"ID: {self.atleta_id} | Nome: {self.nome} | Contato: {self.contato} | Mod: {self.modalidade_final} | Time: {self.time_secretaria}"

class Confronto:
    def _init(self, id, modalidade, time_a=None, time_b=None):
        self.id = id_
        self.modalidade = modalidade
        self.time_a = time_a
        self.time_b = time_b
        self.data_hora = None
        self.local = ''
        self.vencedor = None
        # NOVA LISTA PARA PLACAR (ex: ["25-10", "25-15"])
        self.placar_detalhado = []

    def _str_(self):
        status = f"VENCEDOR: {self.vencedor}" if self.vencedor else "PENDENTE"
        agendamento = f"{self.data_hora.strftime('%d/%m %H:%M')} em {self.local}" if self.data_hora else "NÃO AGENDADO"
        time_b_nome = self.time_b if self.time_b else "BYE (Folga)"
        # Exibe placar se existir
        placar_str = f" | Placar: {', '.join(self.placar_detalhado)}" if self.placar_detalhado else ""

        return f"[ID {self.id}] {self.modalidade}: {self.time_a} vs {time_b_nome} | {status} {placar_str} | {agendamento}"

# ============================
# 4. FUNÇÕES DE IMPORTAÇÃO (PANDAS)
# ============================

def importar_atletas_excel():
    """Importa lista de atletas com validação estrita (Regex/Listas)."""
    print("\n--- Importação de Atletas ---")
    caminho = input("Arquivo (ex: atletas.xlsx): ")
    if not os.path.exists(caminho): return print("❌ Arquivo não encontrado.")

    try: df = pd.read_excel(caminho)
    except Exception as e: return print(f"❌ Erro: {e}")

    global BIBLIOTECA_ATLETAS
    proximo_id = (max(BIBLIOTECA_ATLETAS.keys()) + 1) if BIBLIOTECA_ATLETAS else 1
    sucessos = 0
    erros = 0

    for index, row in df.iterrows():
        try:
            nome_raw = str(row['Nome Completo']).strip()
            padrao = re.compile(r'^[a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÊÍÏÓÔÕÖÚÇÑ\s]+$')
            if not padrao.match(nome_raw): erros += 1; continue
            nome = nome_raw.title()

            contato = str(row['Telefone']).strip()

            sexo = str(row['Gênero']).strip().lower()
            if sexo not in GENERO_PERMITIDO: erros += 1; continue

            mod_raw = str(row['Modalidade']).strip().title()
            if mod_raw == "Vôlei De Areia": mod_raw = "Vôlei de areia"
            if mod_raw == "Tênis De Campo": mod_raw = "Tênis de campo"
            if mod_raw not in ESPORTES_PERMITIDOS: erros += 1; continue

            sec_raw = str(row['Secretaria Acadêmica']).strip()
            if sec_raw.upper() == "CAASO": sec_raw = "AAACSC (CAASO)"
            if sec_raw not in SECRETARIAS_VALIDAS: erros += 1; continue

            novo = Atleta(proximo_id, nome, contato, sexo, mod_raw, sec_raw)
            BIBLIOTECA_ATLETAS[proximo_id] = novo
            proximo_id += 1
            sucessos += 1
        except:
            erros += 1; continue

    print(f"✅ Importação concluída. Sucessos: {sucessos} | Erros: {erros}")

def importar_disponibilidade_excel():
    """Lê grades de disponibilidade (0,1,2) das abas do Excel."""
    print("\n--- Importação de Disponibilidade ---")
    caminho = input("Arquivo (ex: INTERCURSOS-2026.xlsx): ")
    if not os.path.exists(caminho): return print("❌ Arquivo não encontrado.")

    global DISPONIBILIDADE_TIMES
    try: xls = pd.read_excel(caminho, sheet_name=None, header=None)
    except Exception as e: return print(f"❌ Erro: {e}")

    print("Processando...")
    dias_semana = ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"]
    horarios = ["18:00", "19:00", "20:00", "21:00"]
    count = 0

    for sheet_name, df in xls.items():
        nome_sec = sheet_name.strip()
        for sv in SECRETARIAS_VALIDAS:
            if sheet_name.upper() in sv.upper() or sv.split(' ')[0].upper() in sheet_name.upper():
                nome_sec = sv; break

        if nome_sec not in DISPONIBILIDADE_TIMES: DISPONIBILIDADE_TIMES[nome_sec] = {}

        for nome_planilha, nome_sistema in DE_PARA_MODALIDADES.items():
            locs = np.where(df == nome_planilha)
            if len(locs[0]) > 0:
                r, c = locs[0][0], locs[1][0]
                try:
                    bloco = df.iloc[r+2 : r+6, c+1 : c+6].to_numpy()
                    agenda = {}
                    for d, dia in enumerate(dias_semana):
                        agenda[dia] = []
                        for h, hora in enumerate(horarios):
                            if bloco[h][d] == 1: agenda[dia].append(hora)
                    DISPONIBILIDADE_TIMES[nome_sec][nome_sistema] = agenda
                except: continue
        count += 1
    print(f"✅ Disponibilidade de {count} abas processada.")

# ============================
# 5. FUNÇÕES DE CRUD (MANUAL)
# ============================

def cadastrar_atleta():
    print("\n--- Cadastro Manual de Atleta ---")
    global BIBLIOTECA_ATLETAS

    while True:
        try:
            aid = int(input("ID único: "))
            if aid in BIBLIOTECA_ATLETAS: print("⚠ ID em uso."); continue
            break
        except: print("⚠ Número inválido.")

    while True:
        nm = input("Nome completo: ")
        if re.match(r'^[a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÊÍÏÓÔÕÖÚÇÑ\s]+$', nm) and len(nm.strip())>2:
            nome = nm.strip().title(); break
        print("⚠ Apenas letras e acentos.")

    contato = input("Contato: ")
    print("Categorias:", *[f"{k}-{v.title()}" for k,v in GENERO_MAP.items()])
    try: sexo = GENERO_MAP[int(input("Opção: "))]
    except: sexo = "masculino"; print("⚠ Padrão: Masculino")
    print("Modalidades:", *[f"{k}-{v}" for k,v in ESPORTES_MAP.items()])
    try: esporte = ESPORTES_MAP[int(input("Opção: "))]
    except: esporte = "Futsal"; print("⚠ Padrão: Futsal")
    print("Secretarias:", *[f"{k}-{v}" for k,v in SECRETARIAS_MAP.items()])
    try: time = SECRETARIAS_MAP[int(input("Opção: "))]
    except: time = "AAACSC (CAASO)"; print("⚠ Padrão: CAASO")

    novo = Atleta(aid, nome, contato, sexo, esporte, time)
    BIBLIOTECA_ATLETAS[aid] = novo
    print(f"\n✅ Cadastro: {novo}")

def editar_atleta():
    print("\n--- Edição de Atleta ---")
    try: aid = int(input("ID do atleta: "))
    except: return
    atl = BIBLIOTECA_ATLETAS.get(aid)
    if not atl: return print("❌ Não encontrado.")

    print(f"Editando: {atl}")
    op = input("1-Nome | 2-Contato | 3-Esporte | 4-Time: ")

    if op == '1':
        while True:
            nm = input("Novo nome: ")
            if re.match(r'^[a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÊÍÏÓÔÕÖÚÇÑ\s]+$', nm):
                atl.nome = nm.strip().title(); print("✅ Atualizado."); break
            print("⚠ Inválido.")
    elif op == '2': atl.contato = input("Novo contato: ")
    elif op == '3':
        print("Modalidades:", *[f"{k}-{v}" for k,v in ESPORTES_MAP.items()])
        try:
            novo = ESPORTES_MAP[int(input("Opção: "))]
            atl.esporte_interesse = novo
            atl.modalidade_final = f"{novo} {atl.sexo}"
            print("✅ Atualizado.")
        except: print("❌ Inválido.")
    elif op == '4':
        print("Secretarias:", *[f"{k}-{v}" for k,v in SECRETARIAS_MAP.items()])
        try: atl.time_secretaria = SECRETARIAS_MAP[int(input("Opção: "))]; print("✅ Atualizado.")
        except: print("❌ Inválido.")
    else: print("Opção inválida.")

def cadastrar_administrador():
    print("\n--- Novo Administrador ---")
    global BIBLIOTECA_ADMINISTRADORES
    while True:
        try: aid = int(input("ID único: "));
        except: continue
        if aid not in BIBLIOTECA_ADMINISTRADORES: break
        print("⚠ ID em uso.")
    while True:
        nm = input("Nome: ")
        if re.match(r'^[a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÊÍÏÓÔÕÖÚÇÑ\s]+$', nm):
            nome = nm.strip().title(); break
        print("⚠ Inválido.")
    cont = input("Contato: ")
    sec = input("Setor: ")
    BIBLIOTECA_ADMINISTRADORES[aid] = Administrador(aid, nome, cont, sec)
    print("✅ Cadastrado.")

# ============================
# 6. FUNÇÕES DE TORNEIO E ALOCAÇÃO
# ============================

def gerar_chaveamento():
    global BIBLIOTECA_CONFRONTOS
    print("\n--- Gerar Chaveamento ---")
    mods = sorted(list(set(a.modalidade_final for a in BIBLIOTECA_ATLETAS.values())))
    if not mods: return print("⚠ Sem atletas.")
    for i, m in enumerate(mods): print(f"{i+1} - {m}")
    try: mod = mods[int(input("Opção: "))-1]
    except: return

    base_esporte = next((e for e in ESPORTES_PERMITIDOS if e in mod), "Futsal")
    min_req = MINIMO_JOGADORES.get(base_esporte, 1)
    candidatos = set(a.time_secretaria for a in BIBLIOTECA_ATLETAS.values() if a.modalidade_final == mod)
    qualificados = []

    print(f"\nVerificando quórum ({min_req} jogadores)...")
    for time in candidatos:
        qtd = sum(1 for a in BIBLIOTECA_ATLETAS.values() if a.modalidade_final == mod and a.time_secretaria == time)
        if qtd >= min_req: qualificados.append(time)
        else: print(f"❌ {time} eliminado ({qtd} atletas).")

    if len(qualificados) < 2: return print("⚠ Times insuficientes.")
    random.shuffle(qualificados)
    confrontos = []
    for i in range(0, len(qualificados), 2):
        ta = qualificados[i]
        tb = qualificados[i+1] if i+1 < len(qualificados) else None
        confrontos.append(Confronto(i+1, mod, ta, tb))
    BIBLIOTECA_CONFRONTOS[mod] = confrontos
    for c in confrontos: print(c)

def alocar_jogos():
    global AGENDA, BIBLIOTECA_CONFRONTOS, DISPONIBILIDADE_TIMES
    print("\n--- Agendar Jogos ---")
    mods = [m for m, l in BIBLIOTECA_CONFRONTOS.items() if l]
    if not mods: return print("⚠ Sem chaveamentos.")

    for i, m in enumerate(mods): print(f"{i+1} - {m}")
    try: mod = mods[int(input("Opção: "))-1]
    except: return

    pendentes = [c for c in BIBLIOTECA_CONFRONTOS[mod] if not c.data_hora]
    if not pendentes: return print("✅ Tudo agendado.")

    for i, c in enumerate(pendentes): print(f"{i+1} - {c.time_a} vs {c.time_b or 'BYE'}")
    try: jogo = pendentes[int(input("Jogo: "))-1]
    except: return

    ta, tb = jogo.time_a, jogo.time_b
    if tb and ta in DISPONIBILIDADE_TIMES and tb in DISPONIBILIDADE_TIMES:
        if mod in DISPONIBILIDADE_TIMES[ta] and mod in DISPONIBILIDADE_TIMES[tb]:
            print(f"\n✨ Cruzando horários para {ta} e {tb}...")
            da = DISPONIBILIDADE_TIMES[ta][mod]
            db = DISPONIBILIDADE_TIMES[tb][mod]
            sugs = []
            for dia in ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"]:
                comuns = sorted(list(set(da.get(dia,[])).intersection(set(db.get(dia,[])))))
                for h in comuns: sugs.append(f"{dia} às {h}")

            if sugs:
                for i, s in enumerate(sugs): print(f"{i+1} - {s}")
                print("0 - Manual")
                try:
                    esc = int(input("Escolha: "))
                    if esc > 0:
                        sem, hora = sugs[esc-1].split(' às ')
                        dt = input(f"Data para {sem} (DD/MM/AAAA): ") + f" {hora}"
                    else: raise Exception
                except: dt = input("Data/Hora (DD/MM/AAAA HH:MM): ")
            else: print("⚠ Sem compatibilidade."); dt = input("Data/Hora (DD/MM/AAAA HH:MM): ")
        else: print("ℹ Dados de disponibilidade incompletos."); dt = input("Data/Hora (DD/MM/AAAA HH:MM): ")
    else: print("ℹ Times sem dados de disponibilidade."); dt = input("Data/Hora (DD/MM/AAAA HH:MM): ")

    try:
        jogo.data_hora = datetime.strptime(dt, "%d/%m/%Y %H:%M")
        jogo.local = input("Local: ")
        AGENDA.append({'id': jogo.id, 'modalidade': jogo.modalidade, 'time_a': jogo.time_a,
                       'time_b': str(jogo.time_b), 'data_hora': dt, 'local': jogo.local})
        print("✅ Agendado!")
    except: print("❌ Data inválida.")

# ============================
# 7. RESULTADOS E EXPORTAÇÃO (ATUALIZADO)
# ============================

def ver_tabela_resultados():
    """Gera uma tabela visual com Pandas dos jogos finalizados."""
    global BIBLIOTECA_CONFRONTOS
    dados_tabela = []

    # Varre todas as modalidades e confrontos
    for lista_confrontos in BIBLIOTECA_CONFRONTOS.values():
        for jogo in lista_confrontos:
            if jogo.vencedor: # Apenas jogos finalizados
                # Identifica quem perdeu
                perdedor = jogo.time_b if jogo.vencedor == jogo.time_a else jogo.time_a

                dados_tabela.append({
                    "ID Jogo": jogo.id,
                    "Modalidade": jogo.modalidade,
                    "Vencedor": jogo.vencedor,
                    "Perdedor": perdedor,
                    "Placar Detalhado": ", ".join(jogo.placar_detalhado) # Formata lista em string
                })

    if not dados_tabela:
        print("\n⚠ Nenhum resultado registrado ainda.")
        return

    print("\n--- TABELA DE RESULTADOS ---")
    df = pd.DataFrame(dados_tabela)
    # Ajusta exibição do Pandas para não cortar colunas
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 1000)
    print(df.to_string(index=False))
    print("----------------------------")

def registrar_resultado():
    global BIBLIOTECA_CONFRONTOS
    print("\n--- Registrar Resultados ---")

    # Filtra jogos agendados que ainda não têm vencedor definido
    jogos_pendentes = [j for l in BIBLIOTECA_CONFRONTOS.values() for j in l if j.data_hora and not j.vencedor]

    if not jogos_pendentes:
        return print("⚠ Nenhum jogo pendente de resultado.")

    for i, j in enumerate(jogos_pendentes):
        print(f"{i+1} - {j.modalidade} | {j.time_a} vs {j.time_b}")

    try:
        esc = int(input("Escolha o jogo: "))
        alvo = jogos_pendentes[esc - 1]
    except:
        return print("Escolha inválida.")

    # 1. Definir Vencedor
    print(f"\nQuem venceu?\n1 - {alvo.time_a}\n2 - {alvo.time_b}")
    opt_venc = input("Opção: ")

    if opt_venc == '1':
        ganhador = alvo.time_a
        perdedor = alvo.time_b
    elif opt_venc == '2':
        ganhador = alvo.time_b
        perdedor = alvo.time_a
    else:
        return print("Opção inválida.")

    alvo.vencedor = ganhador

    # 2. Loop de Placar (Sets/Tempos)
    print("\n--- Adicionar Placar (Sets/Tempos) ---")
    print("Digite a pontuação. Digite 'finalizado' para encerrar.")

    placar_temp = []
    set_count = 1

    while True:
        p_ganhador = input(f"Pontos do Ganhador ({ganhador}) no {set_count}º tempo/set: ")
        if p_ganhador.lower() == 'finalizado': break

        p_perdedor = input(f"Pontos do Perdedor ({perdedor}) no {set_count}º tempo/set: ")
        if p_perdedor.lower() == 'finalizado': break

        try:
            # Valida se são números inteiros
            pi_ganhador = int(p_ganhador)
            pi_perdedor = int(p_perdedor)

            # Salva no formato "Ganhador-Perdedor" (ex: "25-10")
            placar_temp.append(f"{pi_ganhador}-{pi_perdedor}")
            set_count += 1
        except ValueError:
            print("⚠ Por favor, digite números inteiros para os pontos.")

    alvo.placar_detalhado = placar_temp
    print(f"✅ Resultado salvo: {ganhador} venceu ({', '.join(placar_temp)})")

def exportar_agenda():
    if not AGENDA: return print("Vazia.")
    pd.DataFrame(AGENDA).to_csv(f"agenda_{datetime.now().strftime('%H%M')}.csv", index=False)
    print("✅ Exportado.")

# ============================
# 8. MENUS E EXECUÇÃO
# ============================

def menu_administrador():
    print("\n--- GESTÃO ---")
    print("1-Chaveamento | 2-Alocar Jogos | 3-Resultados e Placar")
    print("4-Gerenciar Atletas | 5-Gerenciar Secretários")
    print("6-Agenda | 7-Exportar CSV")
    print("8-Importar Atletas (Excel) | 9-Importar Disp (Excel) | 0-Voltar")
    try: return int(input("Opção: "))
    except: return -1

if _name_ == "_main_":
    while True:
        print("\n=== SISTEMA INTERCURSOS ===")
        print("1-Admin | 2-Atleta | 3-Sair")
        op = input(">> ")

        if op == '1':
            if login_administrador():
                while True:
                    op_adm = menu_administrador()
                    if op_adm == 1: gerar_chaveamento()
                    elif op_adm == 2: alocar_jogos()
                    elif op_adm == 3:
                        # Submenu Resultados
                        print("\n--- RESULTADOS ---")
                        sub = input("1-Registrar Resultado/Placar | 2-Ver Tabela Geral: ")
                        if sub == '1': registrar_resultado()
                        elif sub == '2': ver_tabela_resultados() # Função Nova
                        else: print("Opção inválida.")
                    elif op_adm == 4:
                        act = input("1-Listar 2-Editar: ")
                        if act == '2': editar_atleta()
                        elif act == '1':
                            if not BIBLIOTECA_ATLETAS: print("Vazio.")
                            else: [print(a) for a in BIBLIOTECA_ATLETAS.values()]
                        else: print("Inválido.")
                    elif op_adm == 5:
                        act = input("1-Listar 2-Cadastrar: ")
                        if act == '2': cadastrar_administrador()
                        elif act == '1':
                            if not BIBLIOTECA_ADMINISTRADORES: print("Vazio.")
                            else: [print(a) for a in BIBLIOTECA_ADMINISTRADORES.values()]
                        else: print("Inválido.")
                    elif op_adm == 6: [print(j) for j in AGENDA] if AGENDA else print("Vazia.")
                    elif op_adm == 7: exportar_agenda()
                    elif op_adm == 8: importar_atletas_excel()
                    elif op_adm == 9: importar_disponibilidade_excel()
                    elif op_adm == 0: break
                    else: print("Opção inválida.")

        elif op == '2': cadastrar_atleta()
        elif op == '3': print("Até logo!"); break
        else: print("Opção inválida.")